# Program aliases
alias 'fire=firebase'
alias 'j=jump'
alias 'pip=pip3'
alias 'py=python3'
alias 'python=python3'
alias 'rs=redshift'
alias 't=tmux'
alias 'tx=tmuxinator'
alias 'tas=tmux attach-session -t'
alias 'tks=tmux kill-session -t'
alias 'vi=vim'
# Bash commands
alias 'fetch=neofetch' # Set whatever you want your screenfetch to be here
#alias 'fetch=fortune | cowsay -f stegosaurus | lolcat'
alias 'clear=clear && fetch'
alias 'lol=lolcat'
# Youtube-dl
alias 'youtube-dla=youtube-dl --extract-audio --audio-format mp3 --no-playlist'
alias 'youtube-dlap=youtube-dl --extract-audio --audio-format mp3'
# Git
alias 'g=git'
alias 'gs=git status'
alias 'ga=git add'
alias 'a=git add'
alias 'gc=git commit'
alias 'gcm=git commit -m'
alias 'gp=git push'
alias 'gpl=git pull'
alias 'gsync=git pull; git push'
alias 'gd=git diff'
alias 'gdc=git diff --cached'
alias 'gi=git init'
alias 'gl=git log'
alias 'gr=git reset'
alias 'grest=git restore'
alias 'grb=git rebase'
alias 'grv=git revert'
alias 'gsw=git switch'
alias 'gm=git merge'
alias 'gmd=git checkout dev && git pull && git checkout - && git merge dev'
alias 'gmm=git checkout main && git pull && git checkout - && git merge main'
alias 'gmmas=git checkout master && git pull && git checkout - && git merge master'
alias 'gb=git branch'
alias 'gst=git stash'
alias 'gstp=git stash push'
alias 'gstsh=git stash show -p'
alias 'gstpop=git stash pop'
alias 'gstd=git stash drop'
alias 'gstl=git stash list'
[alias]
    # Displays branches by most recent commit, with fancy formatting https://stackoverflow.com/questions/5188320/how-can-i-get-a-list-of-git-branches-ordered-by-most-recent-commit
    gbr = "!r() { refbranch=$1 count=$2; git for-each-ref --sort=-committerdate refs/heads --format='%(refname:short)|%(HEAD)%(color:yellow)%(refname:short)|%(color:bold green)%(committerdate:relative)|%(color:blue)%(subject)|%(color:magenta)%(authorname)%(color:reset)' --color=always --count=${count:-20} | while read line; do branch=$(echo \"$line\" | awk 'BEGIN { FS = \"|\" }; { print $1 }' | tr -d '*'); ahead=$(git rev-list --count \"${refbranch:-master}..${branch}\"); behind=$(git rev-list --count \"${branch}..${refbranch:-master}\"); colorline=$(echo \"$line\" | sed 's/^[^|]*|//'); echo \"$ahead|$behind|$colorline\" | awk -F'|' -vOFS='|' '{$5=substr($5,1,70)}1' ; done | ( echo \"ahead|behind||branch|lastcommit|message|author\\n\" && cat) | column -ts'|';}; r"
