# Program aliases
alias 'fire=firebase'
alias 'j=jump'
alias 'pip=pip3'
alias 'py=python3'
alias 'python=python3'
alias 'rs=redshift'
alias 't=tmux'
alias 'tas=tmux attach-session -t'
alias 'tks=tmux kill-session -t'
alias 'vi=vim'
# Bash commands
alias 'fetch=screenfetch' # Set whatever you want your screenfetch to be here
#alias 'fetch=fortune | cowsay -f stegosaurus | lolcat'
alias 'clear=clear && fetch'
alias 'lol=lolcat'
alias 'suu=sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y'
# Youtube-dl
alias 'youtube-dla=youtube-dl --extract-audio --audio-format mp3 --no-playlist'
alias 'youtube-dlap=youtube-dl --extract-audio --audio-format mp3'
# Git
alias 'g=git'
alias 'gs=git status'
alias 'ga=git add'
alias 'a=git add'
alias 'gc=git commit'
alias 'gcm=git commit -m'
alias 'gp=git push'
alias 'gpl=git pull'
alias 'gsync=git pull; git push'
alias 'gd=git diff'
alias 'gdc=git diff --cached'
alias 'gi=git init'
alias 'gl=git log'
alias 'gr=git reset'
alias 'grb=git rebase'
alias 'grv=git revert'
alias 'gch=git checkout'
alias 'gm=git merge'
alias 'gmd=git checkout dev && git pull && git checkout - && git merge dev'
alias 'gmm=git checkout master && git pull && git checkout - && git merge master'
alias 'gb=git branch'
alias 'gst=git stash'
alias 'gsts=git stash save'
alias 'gstsh=git stash show -p'
alias 'gstp=git stash pop'
alias 'gstd=git stash drop'
alias 'gstl=git stash list'

