# tmux
alias 't=tmux'
alias 'ta=tmux attach-session'
# Youtube-dl
alias 'youtube-dla=youtube-dl --extract-audio --audio-format mp3 --no-playlist'
alias 'youtube-dlap=youtube-dl --extract-audio --audio-format mp3'
# Git
alias 'g=git'
alias 'gs=git status'
alias 'ga=git add'
alias 'a=git add'
alias 'gc=git commit'
alias 'gcm=git commit -m'
alias 'gp=git push'
alias 'gpl=git pull'
alias 'gsync=git pull; git push'
alias 'gd=git diff'
alias 'gdc=git diff --cached'
alias 'gi=git init'
alias 'gl=git log'
alias 'gr=git reset'
alias 'grb=git rebase'
alias 'grv=git revert'
alias 'gch=git checkout'
alias 'gm=git merge'
alias 'gb=git branch'
alias 'gst=git stash'
alias 'gsts=git stash save'
alias 'gstsh=git stash show -p'
alias 'gstp=git stash pop'
alias 'gstd=git stash drop'
alias 'gstl=git stash list'
# Program aliases
alias 'lol=lolcat'
alias 'python=python3'
alias 'py=python3'
alias 'pip=pip3'
alias 'rs=redshift'
alias 'vi=vim'
alias 'cb=xclip -sel c'
# Bash commands
alias 'clear=clear && neofetch'
alias 'suu=sudo apt update -y && sudo apt upgrade -y'

